fix linting failing because of Python >= 3.10 assignment operator
scripts/generate_logs.py:51: error: Assignment expressions are only supported in Python 3.8 and greater